CREATE TABLE blocks (
    number BIGINT PRIMARY KEY,
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE object_mappings (
    hash TEXT NOT NULL PRIMARY KEY,
    piece_index INTEGER NOT NULL,
    piece_offset INTEGER NOT NULL,
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);